accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from .views import SignUp,ProfileView,ProfileUpdate,RelationCreate

app_name = "accounts"

urlpatterns = [
    path('login/',LoginView.as_view(template_name = "accounts/login.html"),name="login"),
    path('logout/',LogoutView.as_view(template_name = "accounts/logout.html"),name="logout"),
    path('signup/',SignUp,name="signup"),
    path('profile/<int:pk>/',ProfileView.as_view(),name="profile"),
    path("profile/update/<int:pk>",ProfileUpdate.as_view(), name="profile_update"),
    path('relation/create/<int:pk>',RelationCreate.as_view(),name="relation_create"),
]

photo/urls.py
from django.urls import path
from .views import (PhotoList,PhotoCreate,PhotoDelete,PhotoDetail,PhotoUpdate,PhotoLike,PhotoFavorite,PhotoLikeList,
                    PhotoFavoriteList,PhotoFeed,CommentDelete)

app_name = 'photo'
urlpatterns = [
    path("all_view/",PhotoList.as_view(),name="all_view"),
    path("",PhotoFeed.as_view(),name="index"),
    path("detail/<int:pk>/", PhotoDetail.as_view(), name="detail"),
    path("update/<int:pk>/",PhotoUpdate.as_view(),name="update"),
    path("create/" ,PhotoCreate.as_view(), name="create"),
    path("delete/<int:pk>/", PhotoDelete.as_view(), name="delete"),
    path("like/<int:photo_id>/",PhotoLike.as_view(),name="like"),
    path("favorite/<int:photo_id>/", PhotoFavorite.as_view(), name="favorite"),
    path("like/",PhotoLikeList.as_view(),name="like_list"),
    path("favorite/", PhotoFavoriteList.as_view(), name="favorite_list"),
    path("comment/delete/<int:pk>/", CommentDelete.as_view(), name="comment_delete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    nick_name = models.CharField(max_length=32,blank=True)
    profile_photo = models.ImageField(blank=True,null=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return f'{self.user.id}'


class FollowerRelation(models.Model):
    follower = models.OneToOneField(User,related_name="follower",on_delete=models.CASCADE)
    followee = models.ManyToManyField(User,related_name="followee")

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Profile

class SignUpForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    repeat_password = forms.CharField(label="Repeat Password",widget=forms.PasswordInput)

    class Meta:
        model = User
        # 입력 받을 필드 선언
        fields = ["username","password","repeat_password","email",]

    def clean_repeat_password(self):
        cd = self.cleaned_data
        if cd['password'] != cd["repeat_password"]:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다.")
        return cd['repeat_password']

class ProfileUploadForm(forms.ModelForm):
    model = Profile
    fields = ["nick_name","profile_photo",]

accounts/views.py
from django.shortcuts import render,reverse
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from django.views.generic import UpdateView,CreateView
from .forms import SignUpForm
from photo.models import Photo
from .models import Profile,FollowerRelation
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views import View
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from urllib.parse import urlparse

@method_decorator(csrf_exempt,name="dispatch")
class BaseView(View):
    @staticmethod
    def response(data={},message="",status=200):
        result = {
            "data": data,
            "message": message,
        }
        return JsonResponse(result,status)

def SignUp(request):
    '''회원가입 자동으로 프로필 객체 생성'''
    if request.method == "POST":
        signup_form = SignUpForm(request.POST)

        if signup_form.is_valid():
            user_instance = signup_form.save(commit=False)# 밑에 저장이 있으므로 commit false
            user_instance.set_password(signup_form.cleaned_data['password'])
            user_instance.save()
            user_profile = Profile.objects.create(user=user_instance, profile_photo="/default_user.jpg")
            user_profile.save()
            return render(request,"accounts/signup_complete.html",{"username":user_instance.username})


    else:
        signup_form = SignUpForm()

    return render(request,"accounts/signup.html",{"form":signup_form.as_p})

@method_decorator(login_required,name="dispatch")
class ProfileView(DetailView):
    '''프로필 뷰'''
    context_object_name = "profile_user"
    model= User
    template_name = "accounts/profile.html"

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        object_posts = Photo.objects.filter(author=self.get_object())
        context['object_posts'] = object_posts
        context['post_numbers'] = object_posts.count()
        try:
            request_user_following = list(
                FollowerRelation.objects.get(follower=user).followee.all().values_list("id", flat=True))
            context["request_user_following"] = request_user_following
        except:
            pass
        try:
            followers = FollowerRelation.objects.get(follower=self.get_object()).followee.all() # 팔로잉
            context['followees'] = followers
            context['followees_ids'] = list(followers.values_list('id',flat=True)) #프로필에 있는 유저가 팔로우하는 사람들

        except FollowerRelation.DoesNotExist:
            pass

        context["object_followers"] = FollowerRelation.objects.select_related("follower").filter(followee__in=[self.get_object()]) # 팔로워
        return context

@method_decorator(login_required,name="dispatch")
class ProfileUpdate(UpdateView):
    '''프로필 업데이트'''
    model = Profile
    template_name = "accounts/profile_update.html"
    fields = ["nick_name","profile_photo"]
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.user != request.user:
            return HttpResponseRedirect(str(request.user.id))
        else:
            return super(ProfileUpdate,self).dispatch(request,*args,**kwargs)


@method_decorator(login_required,name="dispatch")
class RelationCreate(BaseView):
    '''
     follow unfollow 기능 한번 누르면 팔로우 또 한 번 누르면 언팔
    '''
    def get(self,request,*args,**kwargs):
        if "pk" in kwargs:
            user = request.user
            user_id = kwargs["pk"]
            try:
                relation = FollowerRelation.objects.get(follower=user)
            except FollowerRelation.DoesNotExist:
                relation = FollowerRelation.objects.create(follower=user)

            followees = list(FollowerRelation.objects.filter(follower=user).values_list('followee__id', flat=True))

            if user.id in followees:
                relation.followee.remove(user)
            if user_id in followees:
                relation.followee.remove(user_id)
            else:
                relation.followee.add(user_id)

        referer_url = request.META.get("HTTP_REFERER")
        path = urlparse(referer_url).path
        return HttpResponseRedirect(path)

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="'">
        <div class="alert_alert-primary">로그인</div>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="login" class="btn btn-primary">
    </form>
</div>
<div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="">
        <div class="alert_alert-primary">로그아웃 되었습니다.</div>
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">로그인 하기</a>
</div>
<div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load thumbnail %}

<div class="row">
    <div class="col"></div>
    <div class="col-xs-6 col-md-2">
        {% if profile_user.profile.profile_photo %}
        <img class="round" src="{{profile_user.profile.profile_photo.url}}" width="200"> <br>
        {% else %}
        <img class="round" src="{% static 'default_profile/default_user.jpg' %}" width="200"> <br>
        {% endif %}
    </div>
    <div class="col-xs-6 col-md-3">
        <h3 style="margin-left:15px;"> {{profile_user.username}}
            {% if request.user == profile_user %}   <!-- 로그인한 사용자와 profile_user(프로필 소유자)가 일치할 때만 프로필 편집이 가능하도록 함 -->
        <a href="{%url 'accounts:profile_update' request.user.id%}">
            <button type="button" class="btn btn-secondary">프로필 편집</button></a></h2>
        {% endif %}

            {% if request.user != profile_user %}
            {% if profile_user.id in request_user_following %}
            <a href="{%url 'accounts:relation_create' profile_user.id %}"><button  type="button" class="btn btn-secondary" >언팔로우</button></a>
            {% else %}
            <a href="{%url 'accounts:relation_create' profile_user.id %}"><button  type="button" class="btn btn-secondary" >팔로우</button></a>
            {% endif %}

            {% endif %}
            <br>
        </h3>
        <p></p>
        <span style="margin-left:15px;">게시글: <strong>{{post_numbers}}</strong> </span> <span id="follower">팔로워: <strong>{{object_followers.count}}</strong></span> <span id="follow">팔로우:<strong>{% if not followees.count %}0{%else%}{{followees.count}}{% endif %}</strong></span>
    </div>
    <div class="col"></div>
</div>
<div class="row" style="margin-top: 50px;">

            {% for post in object_posts%}
            <div class="col-xs-6 col-md-4">

            {% thumbnail post.image "300x300" crop="center" as im %}
                <a href="{% url 'photo:detail' post.id %}"><img src="{{im.url}}" width="{{im.width}}" height="{{im.height}}"/></a>
                {% endthumbnail %}
            </div>
            {% endfor %}

</div>

<div class="modal" tabindex="-1" role="dialog" id="Myfollower">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">팔로워</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% if object_followers %}
        {% for obj in object_followers%}
          <li class="media">
                <a href="{% url 'accounts:profile' obj.follower.id  %}"><img class="round "src="{{obj.follower.profile.profile_photo.url}}" class="mr-3" alt="..." width="30" style="margin-right:15px;"></a>
                <div class="media-body">
                     <h5 class="mt-0"> <strong>{{obj.follower.username}}</strong></h5>
                </div>
          </li>

        {% endfor %}
        {% else %}
        <p>&nbsp;팔로워가 없습니다.</p>
        {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" tabindex="-1" role="dialog" id="Myfollow">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">팔로우</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% if followees %}
        {% for followee in followees %}
          <li class="media">
                <a href="{% url 'accounts:profile' followee.id %}"><img class="round "src="{{followee.profile.profile_photo.url}}" class="mr-3" alt="..." width="30" style="margin-right:15px;"></a>
                <div class="media-body">
                     <h5 class="mt-0"> <strong>{{followee.username}}</strong></h5>
                </div>
          </li>
        {% endfor %}
        {% else %}
        <p>팔로워가 없습니다.</p>
        {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function(){
    $("#follower").click(function(){
        $("#Myfollower").modal();
    });
});
$(document).ready(function(){
    $("#follow").click(function(){
        $("#Myfollow").modal();
    });
});

</script>
{% endblock %}

accounts/templates/accounts/profile_update.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert_alert-primary">모든 부분을 다 넣어주세요.</div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="업로드" class="btn btn-primary">
    </form>
</div>
<div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="'">
        <div class="alert_alert-primary">회원가입</div>
    <form action="." method="post">
        {% csrf_token %}
        <div>{{ error }}</div>
        {{form}}
<!--        <div><label for="">사용자 이름<input type="text" name="username"></label></div>-->
<!--        <div><label for="">비밀번호<input type="password" name="password"></label></div>-->
<!--        <div><label for="">비밀번호 확인<input type="password" name="password2"></label></div>-->
        <input type="submit" value="signup" class="btn btn-primary">
    </form>
</div>
<div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/signup_complete.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="alert alert-primary" role="alert">
            회원가입이 성공적으로 완료되었습니다.
            <a href="{% url 'accounts:login'%}">로그인으로 이동하기</a>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

accounts/templates/accounts/user_list.html
{% extends "base.html" %}

{% block content %}
{{request.user 님}}
{% for object in object_list %}
<tr>
    <td>{[object.username}}</td>
    <td><a href="{% url 'accounts:following' object.id %}" class="btn btn-xs btn-outline-success">Follow</a></td>

    <td><a href="{% url 'accounts:unfollow' object.id %}" class="btn btn-xs btn-outline-success">UnFollow</a></td>
</tr>

{% endfor%}
{% if follower %}
<h2>날 팔로우 하는 사람들</h2>
<ul>{% for obj in follower%}
    <li>{{obj.follwer.username}}{% if obj.follower.id not in following.ids %}</li><button class="follow" data-user-id="{{user.id}}">팔로우</button>
    {% endfor %}
</ul>
{% endif %}

{% if following %}
<h2>내가 팔로우 하는 사람들</h2>
<ul>
    {% for user in following %}
    <li>{{user.username}}</li><button class="unnollow" data-user-id="{{user.id}}">언팔로우</button>
    {% endfor %}
</ul>

{% endblock %}