accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from .views import SignUp,ProfileView,ProfileUpdate,RelationCreate

app_name = "accounts"

urlpatterns = [
    path('login/',LoginView.as_view(template_name = "accounts/login.html"),name="login"),
    path('logout/',LogoutView.as_view(template_name = "accounts/logout.html"),name="logout"),
    path('signup/',SignUp,name="signup"),
    path('profile/<int:pk>/',ProfileView.as_view(),name="profile"),
    path("profile/update/<int:pk>",ProfileUpdate.as_view(), name="profile_update"),
    path('relation/create/<int:pk>',RelationCreate.as_view(),name="relation_create"),
]

photo/urls.py
from django.urls import path
from .views import (PhotoList,PhotoCreate,PhotoDelete,PhotoDetail,PhotoUpdate,PhotoLike,PhotoFavorite,PhotoLikeList,
                    PhotoFavoriteList,PhotoFeed,CommentDelete)

app_name = 'photo'
urlpatterns = [
    path("all_view/",PhotoList.as_view(),name="all_view"),
    path("",PhotoFeed.as_view(),name="index"),
    path("detail/<int:pk>/", PhotoDetail.as_view(), name="detail"),
    path("update/<int:pk>/",PhotoUpdate.as_view(),name="update"),
    path("create/" ,PhotoCreate.as_view(), name="create"),
    path("delete/<int:pk>/", PhotoDelete.as_view(), name="delete"),
    path("like/<int:photo_id>/",PhotoLike.as_view(),name="like"),
    path("favorite/<int:photo_id>/", PhotoFavorite.as_view(), name="favorite"),
    path("like/",PhotoLikeList.as_view(),name="like_list"),
    path("favorite/", PhotoFavoriteList.as_view(), name="favorite_list"),
    path("comment/delete/<int:pk>/", CommentDelete.as_view(), name="comment_delete"),
]

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from sorl.thumbnail import images
import datetime

# Create your models here.

class Photo(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="user")
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to="timeline_photo/%Y/%m/%d")
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True) # 수정할때마다 갱신
    like = models.ManyToManyField(User,related_name="like_post",blank=True)
    favorite = models.ManyToManyField(User,related_name="favorite_post",blank=True)
    is_public = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.text}"

    class Meta:
        ordering = ['-created'] # created순으로 정렬

    def get_absolute_url(self):
        return reverse("photo:detail",args=[self.id])

class Comment(models.Model):
    photo = models.ForeignKey(Photo,on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_content = models.CharField(max_length=300)

    class Meta:
        ordering = ['-comment_date']

photo/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_content']

photo/views.py
from django.http import HttpResponseRedirect
from django.http import HttpResponseForbidden
from urllib.parse import urlparse
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from .models import Photo,Comment
from django.shortcuts import redirect
from django.contrib import messages
from django.views.generic.base import View
from .forms import CommentForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accounts.models import FollowerRelation,Profile
from django.contrib.auth import get_user_model


# def chk_requser_objuser(obj_usr,req_usr):
#     if obj_usr != req_usr:
#         return False
#     return True

class PhotoList(LoginRequiredMixin,ListView):
    # 모든 유저들의 게시글을 볼 수 있음
    login_url = "/accounts/login"
    redirect_field_name = 'redirect_to'
    model = Photo
    template_name_suffix = "_list"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PhotoList,self).get_context_data(**kwargs)
        return context

@method_decorator(login_required,name='dispatch')
class PhotoFeed(ListView):
    # 팔로우한 사람 게시글만 볼 수 있음
    template_name_suffix = "_feed"
    model = Photo
    paginate_by = 1

    def get_context_data(self,**kwargs):
        context = super(PhotoFeed,self).get_context_data(**kwargs)
        user = self.request.user
        followees = FollowerRelation.objects.filter(follower=user).values_list("followee__id",flat=True)
        lookup_user_ids = [user.id] + list(followees)
        context['contents'] = Photo.objects.select_related("author").filter(author__id__in = lookup_user_ids)
        User = get_user_model()
        can_follow_users_list = User.objects.exclude(id__in=lookup_user_ids)
        context["can_follow_users_list"] = can_follow_users_list
        try:
            context['profile'] = Profile.objects.get(user=user)
        except Profile.DoesNotExist:
            user_profile = Profile.objects.create(user=user,profile_photo="/default_user.jpg")
            user_profile.save()
        return context

class PhotoCreate(LoginRequiredMixin,CreateView):
    login_url = "/accounts/login"
    redirect_field_name = 'redirect_to'
    model = Photo
    fields = ["text","image","is_public",]
    template_name_suffix = "_create"

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect("/")

@method_decorator(login_required,name='dispatch')
class PhotoUpdate(UpdateView):
    model = Photo
    fields = ["text","image"]
    template_name_suffix = "_update"
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request,"수정할 권한이 없습니다.")
            return HttpResponseRedirect("/")
        else:
            return super(PhotoUpdate,self).dispatch(request,*args,**kwargs) # 업데이트문을 다시 시작하겠다.

class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = "_delete"
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()

        if object.author != request.user:
            messages.warning(request,"삭제할 권한이 없습니다.")
            return HttpResponseRedirect("/")
        else:
            return super(PhotoDelete,self).dispatch(request,*args,**kwargs)

class PhotoDetail(DetailView,LoginRequiredMixin):
    model = Photo
    template_name_suffix = "_detail"
    # form_class = CommentForm
    context_object_name = "post"

    def get_success_url(self): # post 처리가 성공한뒤
        return reverse("photo:detail",kwargs={"pk":self.object.pk})

    def get_context_data(self, **kwargs): # template 보낼 context 설정
        context = super().get_context_data(**kwargs)
        comments_connected = Comment.objects.filter(photo=self.get_object()).order_by("-comment_date")
        context['comments'] = comments_connected
        context['form'] = CommentForm(instance=self.request.user)
        return context

    def post(self,request,*args,**kwargs):
        new_comment = Comment(comment_content=request.POST.get("comment_content"),author = self.request.user,photo = self.get_object())
        new_comment.save()
        return self.get(self,request,*args,**kwargs)

class PhotoLike(View):
    def get(self,request,*args,**kwargs):
        if not request.user.is_authenticated: # 로그인이 안되어있으면
            return HttpResponseForbidden()
        else:
            if "photo_id" in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.like.all():
                    photo.like.remove(user)
                else:
                    photo.like.add(user)
            referer_url = request.META.get("HTTP_REFERER")
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

class PhotoFavorite(View):
    def get(self,request,*args,**kwargs):
        if not request.user.is_authenticated: # 로그인이 안되어있으면
            return HttpResponseForbidden()
        else:
            if "photo_id" in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.favorite.all():
                    photo.favorite.remove(user)
                else:
                    photo.favorite.add(user)

            referer_url = request.META.get("HTTP_REFERER")
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

class PhotoLikeList(ListView):
    model = Photo
    template_name = "photo/photo_list.html"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request,"로그인이 필요합니다.")
            return HttpResponseRedirect("/")
        return super(PhotoLikeList,self).dispatch(request,*args,**kwargs)

    def get_queryset(self):
        user = self.request.user
        queryset = user.like_post.all()
        return queryset

class PhotoFavoriteList(ListView):
    model = Photo
    template_name = "photo/photo_list.html"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request,"로그인이 필요합니다.")
            return HttpResponseRedirect("/")
        return super(PhotoFavoriteList,self).dispatch(request,*args,**kwargs)

    def get_queryset(self):
        user = self.request.user
        queryset = user.favorite_post.all()
        return queryset



#
class CommentDelete(DeleteView):
    model = Comment
    template_name_suffix = "_delete"
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request,"삭제할 권한이 없습니다.")
            return HttpResponseRedirect("/")
        else:
            return super(CommentDelete,self).dispatch(request,*args,**kwargs)

photo/templates/photo/asdbackup.html
{% extends "base.html" %}
{% block title %}title
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            {% if can_follow_users_list %}
    <h5>회원님을 위한 친구 추천</h5>
  <ul class="list-group list-group-flush">

      {% for usr in can_follow_users_list %}
              <li class="media">
                <a href="{% url 'accounts:profile' usr.profile.user.id%}"><img class="round "src="{{usr.profile.profile_photo.url}}" class="mr-3" alt="..." width="30" style="margin-right:15px;"></a>
                <div class="media-body">
                     <h5 class="mt-0"> <strong>{{usr.username}}</strong><a href="{%url 'accounts:relation_create' usr.profile.user.id %}" class="float-right"><button type="button" class="btn btn-secondary">팔로우</button></a></h5>
                </div>
              </li>
            {% endfor %}
  </ul>
            {% endif %}
</div>

        <div class="col-5">
            {% if contents %}
            {% for content in contents %}
            <div class="card infinite-item">
                <div class="card-header">
                    <img src="{{content.author.profile.profile_photo.url}}" style="margin-right:10px;" class="round" width="50" alt=""><a href="{% url 'accounts:profile' content.author.id %}">{{ content.author.username }}</a>
                </div>
                <img src="{{content.image.url}}" class="card-img-top" alt="">
                <div class="card-body">
                    <p class="card-text">{{content.text}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    {% if user.is_authenticated %}
                    <li class="list-group-item"><a href="{% url 'photo:like' content.id %}" class="float-left btn-like {%if user in content.like.all%} active {% endif %}">좋아요</a>
                    {% if content.like.all.count %}
                        <span class="float-left">{{content.like.all.count}}</span>
                        {% endif %}
                        <a href="{% url 'photo:favorite' content.id %}" class="float-right btn-favorite {% if user in content.favorite.all %}active{%endif%}">저장하기</a>
                    </li>
                    {% endif %}
                    <li class="list-group-item">생성일 : {{content.created}}</li>
                </ul>
                <div class="card-body">
                    {% for comment in content.comments.all %}
                    <div><strong><a href="{% url 'accounts:profile' comment.author.id%}">{{comment.author}}</a></strong>: {{comment.comment_content}}</div>
                    {% endfor %}
                </div>

                <div class="card-body">
                    <a href="{% url 'photo:detail' content.id %}" class="card-link" style="float:right;">댓글달기</a>
                </div>

            </div>
            {% endfor %}
                            {% if page_obj.has_next %}
                <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
                {% endif %}
                <div class="d-flex justify-content-center" style="display:none;">
                    <div class="spinner-border" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
            </div>

         {% endif %}

                    <ul class="list-unstyled col-md-4">
  <li class="media">
                <a href="{% url 'accounts:profile' profile.user.id %}"><img class="round "src="{{profile.profile_photo.url}}" class="mr-3" alt="..." width="100" style="margin-right:15px;"></a>
    <div class="media-body">
                     <h5 class="mt-0"> <strong>{{profile.user.username}}</strong> </h5>
        <h6>{{profile.nick_name}}</h6>
    </div>
  </li>
        </ul>

        </div>


        </div>
    </div>
  </li>

</div>
        </div>
    </div>



<script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        handler: function(direction) {

    },
    offset: 'bottom-in-view',

    onBeforePageLoad: function () {
    $('.spinner-border').show();
    },
    onAfterPageLoad: function () {
    $('.spinner-border').hide();
    }

    });

</script>

{% endblock %}

photo/templates/photo/photo_create.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert_alert-primary">모든 부분을 다 기입해주세요.</div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="업로드" class="btn btn-primary">
    </form>
</div>
<div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_delete.html
{% extends "base.html" %}
{% block content %}
<div class="alert_alert-primary" role="alert">
    정말 {{object}}를 지우시겠습니까?
</div>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete Ok">
</form>

{% endblock %}

photo/templates/photo/photo_detail.html
{% extends "base.html" %}
{% block title %}title
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col-12 col-xl-4 col-md-4">
            <div class="card">
                <img src="{{object.image.url}}" class="card-img-top"alt="">
                <div class="card-body">
                    <h5 class="card-title">{{object.author}}</h5>
                    <p class="card-text">{{object.text}} </p>
                </div>
                <ul class="list-group list-group-flush">
                    {% if user.is_authenticated %}
                    <li class="list-group-item"><a href="{% url 'photo:like' object.id %}" class="float-left btn-like {%if user in object.like.all%} active {% endif %}">좋아요</a>
                    {% if object.like.all.count %}
                        <span class="float-left">{{object.like.all.count}}</span>
                        {% endif %}
                        <a href="{% url 'photo:favorite' object.id %}" class="float-right btn-favorite {% if user in object.favorite.all %}active{%endif%}">저장하기</a>
                    </li>
                    {% endif %}
                    <li class="list-group-item">수정일 : {{object.created}}</li>
                </ul>
                {% if object.author == request.user %}
                <div class="card-body">
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
                </div>
                {% endif %}
                <div class="card-body">
                    {% for comment in comments%}
                    <div><strong><a href="{% url 'accounts:profile' comment.author.id%}">{{comment.author}}</a></strong>: {{comment.comment_content}}</div>
                    {% endfor %}
                </div>
            {% if user.is_authenticated %}
                <form action="" method="post">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="댓글달기" class="btn btn-primary">
                </div>
                    </form>
                {% endif %}
            </div>
        </div>
        <div class="col"></div>
</div>
{% endblock %}

photo/templates/photo/photo_feed.html
{% extends "base.html" %}
{% block title %}title
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            {% if can_follow_users_list %}
    <h5>회원님을 위한 친구 추천</h5>
  <ul class="list-group list-group-flush">

      {% for usr in can_follow_users_list %}
              <li class="media">
                <a href="{% url 'accounts:profile' usr.profile.user.id%}"><img class="round "src="{{usr.profile.profile_photo.url}}" class="mr-3" alt="..." width="30" style="margin-right:15px;"></a>
                <div class="media-body">
                     <h5 class="mt-0"> <strong>{{usr.username}}</strong><a href="{%url 'accounts:relation_create' usr.profile.user.id %}" class="float-right"><button type="button" class="btn btn-secondary">팔로우</button></a></h5>
                </div>
              </li>
            {% endfor %}
  </ul>
            {% endif %}
</div>

        <div class="col-5">
            {% if contents %}
            {% for content in contents %}
            <div class="card infinite-item">
                <div class="card-header">
                    <img src="{{content.author.profile.profile_photo.url}}" style="margin-right:10px;" class="round" width="50" alt=""><a href="{% url 'accounts:profile' content.author.id %}">{{ content.author.username }}</a>
                </div>
                <img src="{{content.image.url}}" class="card-img-top" alt="">
                <div class="card-body">
                    <p class="card-text">{{content.text}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    {% if user.is_authenticated %}
                    <li class="list-group-item"><a href="{% url 'photo:like' content.id %}" class="float-left btn-like {%if user in content.like.all%} active {% endif %}">좋아요</a>
                    {% if content.like.all.count %}
                        <span class="float-left">{{content.like.all.count}}</span>
                        {% endif %}
                        <a href="{% url 'photo:favorite' content.id %}" class="float-right btn-favorite {% if user in content.favorite.all %}active{%endif%}">저장하기</a>
                    </li>
                    {% endif %}
                    <li class="list-group-item">생성일 : {{content.created}}</li>
                </ul>
                <div class="card-body">
                    {% for comment in content.comments.all %}
                    <div><strong><a href="{% url 'accounts:profile' comment.author.id%}">{{comment.author}}</a></strong>: {{comment.comment_content}}</div>
                    {% endfor %}
                </div>

                <div class="card-body">
                    <a href="{% url 'photo:detail' content.id %}" class="card-link" style="float:right;">댓글달기</a>
                </div>

            </div>
            {% endfor %}
                <div class="col">
                </div>
            </div>

         {% endif %}

                    <ul class="list-unstyled col-md-4">
  <li class="media">
                <a href="{% url 'accounts:profile' profile.user.id %}"><img class="round "src="{{profile.profile_photo.url}}" class="mr-3" alt="..." width="100" style="margin-right:15px;"></a>
    <div class="media-body">
                     <h5 class="mt-0"> <strong>{{profile.user.username}}</strong> </h5>
        <h6>{{profile.nick_name}}</h6>
    </div>
  </li>
        </ul>

        </div>


        </div>
    </div>
  </li>

</div>
        </div>
    </div>



<script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        handler: function(direction) {

    },
    offset: 'bottom-in-view',

    onBeforePageLoad: function () {
    $('.spinner-border').show();
    },
    onAfterPageLoad: function () {
    $('.spinner-border').hide();
    }

    });

</script>

{% endblock %}

photo/templates/photo/photo_list.html
{% extends "base.html" %}
{% block title %}title
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-5">
            {% for object in object_list %}
            <div class="card">
                <div class="card-header">

                    <img src="" alt=""><a href="{%url 'accounts:profile' object.id %}">{{ object.author }}</a>
                </div>
                <img src="{{object.image.url}}" class="card-img-top" alt="">
                <div class="card-body">
                    <p class="card-text">{{object.text}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    {% if user.is_authenticated %}
                    <li class="list-group-item"><a href="{% url 'photo:like' object.id %}" class="float-left btn-like {%if user in object.like.all%} active {% endif %}">좋아요</a>
                    {% if object.like.all.count %}
                        <span class="float-left">{{object.like.all.count}}</span>
                        {% endif %}
                        <a href="{% url 'photo:favorite' object.id %}" class="float-right btn-favorite {% if user in object.favorite.all %}active{%endif%}">저장하기</a>
                    </li>
                    {% endif %}
                    <li class="list-group-item">생성일 : {{object.created}}</li>
                </ul>
                <div class="card-body">
                    {% for comment in object.comments.all %}
                    <div><strong><a href="{% url 'accounts:profile' comment.author.id%}">{{comment.author}}</a></strong>: {{comment.comment_content}}</div>
                    {% endfor %}
                </div>

                <div class="card-body">
                    <a href="{% url 'photo:detail' object.id %}" class="card-link" style="float:right;">댓글달기</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if user %}
        <div class="col"></div>
        {% endif %}

    </div>


</div>
{% endblock %}

photo/templates/photo/photo_update.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Update">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}